Update MINISHELL_TESTER.yml

diff --git a/.github/workflows/MINISHELL_TESTER.yml b/.github/workflows/MINISHELL_TESTER.yml
--- a/.github/workflows/MINISHELL_TESTER.yml
+++ b/.github/workflows/MINISHELL_TESTER.yml
@@ -31,9 +31,12 @@ jobs:
         continue-on-error: true
         run: |
           norminette . | tee norm.txt
+          norm_exit = ${PIPELINE[0]}
+          exit $norm_exit
 
       - name: Final result (For norminette)
-        run: | 
+        run: |
+          echo "Errors"
           error_count=$(grep -c "Error" norm.txt || true)
           if [[ "${{ steps.norm.outcome }}" == "success" ]]; then
           echo -e "\033[0;32m✅ Norminette succeeded\033[0m"
