Update MINISHELL_TESTER.yml

diff --git a/.github/workflows/MINISHELL_TESTER.yml b/.github/workflows/MINISHELL_TESTER.yml
--- a/.github/workflows/MINISHELL_TESTER.yml
+++ b/.github/workflows/MINISHELL_TESTER.yml
@@ -28,15 +28,15 @@ jobs:
         
       - name: Run norminette
         id: norm
-        run: norminette
         continue-on-error: true
+        run: |
+          norminette . | tee norm.txt
 
       - name: Final result (For norminette)
-        run: |
+        run: | 
+          error_count=$(grep -c "Error" norm.txt || true)
           if [[ "${{ steps.norm.outcome }}" == "success" ]]; then
-            # Green text: \033[0;32m … \033[0m
-            echo -e "\033[0;32m✅ Norminette succeeded\033[0m"
+          echo -e "\033[0;32m✅ Norminette succeeded\033[0m"
           else
-            # Red text: \033[0;31m … \033[0m
-            echo -e "\033[0;31m❌ Norminette failed\033[0m"
+          echo -e "\033[0;31m❌ Norminette failed with $error_count error(s)\033[0m"
           fi
